### ISSUE TITLE
Structuring typing.NewType classes

### ISSUE THREAD

**Issue by Savlik** [python-attrs/cattrs#173] opened 2021-10-06 11:01 UTC
* cattrs version: 1.8.0
* Python version: 3.8.10
* Operating System: Linux

### Description

I want to use `typing.NewType` in my code, but structuring these variables throws an exception.

### What I Did

```python
from typing import  NewType
from cattr import GenConverter

c = GenConverter()

MyType = NewType("MyType", str)
initial = MyType("test")

raw = c.unstructure(initial, MyType)
new = c.structure(raw, MyType)
assert initial == new
```

```
Traceback (most recent call last):
  File ".../test.py", line 10, in <module>
    new = c.structure(raw, MyType)
  File ".../lib/python3.8/site-packages/cattr/converters.py", line 294, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File ".../lib/python3.8/site-packages/cattr/converters.py", line 360, in _structure_error
    raise StructureHandlerNotFoundError(msg, type_=cl)
cattr.errors.StructureHandlerNotFoundError: Unsupported type: <function NewType.<locals>.new_type at 0x7fb67c77a0d0>. Register a structure hook for it.
```

Of course, I can explicitly register structure hook for it, but it would be nice if it worked out of the box, if possible.

**Comment by Tinche** [comment] 2022-02-07 02:49
Dupe of #94 ? Might look into this soon though.

**Closed by Tinche** 2022-02-07 02:49 UTC
