### ISSUE TITLE
Confusing error when structuring

### ISSUE THREAD

**Issue by TimothyFitz** [python-attrs/cattrs#59] opened 2019-04-05 23:36 UTC
* cattrs version: 0.9.
* Python version: 3.6.6
* Operating System: Ubuntu 18.04.1

### Description

When structuring an object that has an attribute with type `dict`, cattrs fails with a confusing error message.

It wasn't until after I created a minimal reproduction case and came here to file an issue, thinking it was a bug, that I discovered from #3 that cattrs doesn't support `dict` (or `list`).

I think either these attempting to use these types should fail with a clear error ("`dict` is not a supported type hint for cattrs") or alternatively if possible they should work identically to `typing.Dict`

### What I Did

```python
>>> from attr import attrs, attrib
>>> import cattr
>>> @attrs
... class Foo:
...     bar: dict = attrib()
... 
>>> cattr.structure({'bar': {}}, Foo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/cattr/converters.py", line 178, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "/usr/local/lib/python3.6/dist-packages/cattr/converters.py", line 296, in structure_attrs_fromdict
    conv_obj[name] = dispatch(type_)(val, type_)
  File "/usr/local/lib/python3.6/dist-packages/cattr/converters.py", line 337, in _structure_dict
    if is_bare(cl) or cl.__args__ == (Any, Any):
  File "/usr/local/lib/python3.6/dist-packages/cattr/_compat.py", line 108, in is_bare
    return not type.__args__
AttributeError: type object 'dict' has no attribute '__args__'
```

Thanks for cattrs, overall it's been extremely easy to use and cleaned up a large chunk of braindead-but-easy-to-screw-up serialization code.

**Comment by Eugenio2192** [comment] 2022-01-18 16:46
I know this is old but had the same problem recently. 

The solution is to use typing.Dict (typing.Sequence for lists I suspect) instead of dict in the type definition.

**Comment by Tinche** [comment] 2022-01-18 17:09
Ooph the original issue is from 2019, and just `dict` should absolutely work. Can you share an example?

**Comment by klausmcm** [comment] 2022-02-17 23:58
Not sure if the same issue but this issue seems to be the closest to what I could find.

```python
import attr
import cattr

config = {
    "key1": "value1",
    "key2": "value2",
    "misc": {
        "mkey1": "mvalue1",
        "mkey2": "mvalue2",
    },
}

@attr.s(auto_attribs=True)
class ConfigSchema:
    key1: str
    key2: str
    misc: dict

obj = cattr.structure(config, ConfigSchema)
```

Gives me the following

```
Traceback (most recent call last):
  File "UNITY/test.py", line 19, in <module>
    obj = cattr.structure(config, ConfigSchema)
  File "/home/klaus/Documents/projects/unity/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/cattr/converters.py", line 300, in structure                                                       
    return self._structure_func.dispatch(cl)(obj, cl)
  File "/home/klaus/Documents/projects/unity/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/cattr/dispatch.py", line 49, in _dispatch                                                          
    return self._function_dispatch.dispatch(cl)
  File "/home/klaus/Documents/projects/unity/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/cattr/dispatch.py", line 126, in dispatch                                                          
    return handler(typ)
  File "/home/klaus/Documents/projects/unity/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/cattr/converters.py", line 745, in gen_structure_attrs_fromdict                                    
    **attrib_overrides,
  File "/home/klaus/Documents/projects/unity/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/cattr/gen.py", line 280, in make_dict_structure_fn                                                 
    handler = converter._structure_func.dispatch(t)
  File "/home/klaus/Documents/projects/unity/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/cattr/dispatch.py", line 49, in _dispatch                                                          
    return self._function_dispatch.dispatch(cl)
  File "/home/klaus/Documents/projects/unity/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/cattr/dispatch.py", line 126, in dispatch                                                          
    return handler(typ)
  File "/home/klaus/Documents/projects/unity/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/cattr/converters.py", line 790, in gen_structure_mapping                                           
    h = make_mapping_structure_fn(cl, self)
  File "/home/klaus/Documents/projects/unity/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/cattr/gen.py", line 465, in make_mapping_structure_fn                                              
    if not is_bare(cl):
  File "/home/klaus/Documents/projects/unity/.direnv/python-venv-3.7.3/lib/python3.7/site-packages/cattr/_compat.py", line 171, in is_bare                                                            
    args = type.__args__
AttributeError: type object 'dict' has no attribute '__args__'
```

* Python 3.7.3
* attrs==21.2.0
* cattrs==1.10.0

**Comment by Tinche** [comment] 2022-02-18 00:00
This is fixed on main, still unreleased though. You can install from git and verify it's fixed. 

On earlier Pythons dict type annotations were expected to be `typing.Dicts` instead of just builtin `dicts`, so support for those wasn't added before.

**Comment by klausmcm** [comment] 2022-02-18 06:09
I wanted to try out the current master branch code but couldn't figure out how to install. I tried following https://cattrs.readthedocs.io/en/latest/installation.html#stable-release. I installed **pip-22.0.3** and I cloned the repo. I have a `cattrs` folder and in that folder I ran `pip install -e .` but I get the following error

```
ERROR: Project file:///home/klaus/Documents/cat/cattrs has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
```

Suggestions?

**Comment by klausmcm** [comment] 2022-02-19 00:55
That worked. I can confirm that 3ee4b40fe1fe64a6c68157f9a9abe43e232f69c7 resolves this issue including OP's issue. Is there an ETA for a release with this fix?

**Comment by Tinche** [comment] 2022-02-20 19:13
@klausmcm a couple of weeks, I still need to merge in a big feature I've been working on.

**Comment by klausmcm** [comment] 2022-02-21 00:46
Thank you! I guess you can consider this issue as resolved then.

**Closed** 2022-04-07 13:57 UTC
