### ISSUE TITLE
How do I make an empty container default to None?

### ISSUE THREAD

**Issue by ckp95** [python-attrs/cattrs#333] opened 2023-02-22 17:55 UTC
* cattrs version: 22.2.0
* Python version: 3.8.10
* Operating System: WSL

I want to structure something in a way that turns empty lists into a None, if the target type is Optional[List[str]].

```
from typing import Optional, List
from attrs import define
import cattrs


@define
class Something:
    foo: Optional[List[str]] = None


converter = cattrs.Converter()
converter.register_structure_hook(
    Optional[List[str]],
    lambda _list, _: _list or None
)

primitives = {"foo": []}
result = converter.structure(primitives, Something)
print(result)
```

This gives `Something(foo=[])`. But I want it to give `Something(foo=None)`.

This seems like it should be simple but I just cannot figure it out.

**Comment by Tinche** [comment] 2023-02-22 22:40
Howdy,

so the problem is `register_structure_hook` uses [functools.singledispatch](https://docs.python.org/3/library/functools.html#functools.singledispatch) under the hood, which works mostly like you'd expect when using classes. But something like `Optional[List[str]]` is a more complex generic type, so it won't trigger.

There's an escape hatch though, you can use a predicate function (it's a function that takes a type and returns a bool, whether the hook handles it) instead.

```python
converter.register_structure_hook_func(
    lambda t: t == Optional[List[str]], lambda _list, _: _list or None
)
```
This should work as expected.

**Comment by Tinche** [comment] 2023-03-05 18:19
Going to close this, hope that's ok.

**Closed by Tinche** 2023-03-05 18:19 UTC
