### ISSUE TITLE
cattr.structure converting None

### ISSUE THREAD

**Issue by fwannmacher** [python-attrs/cattrs#53] opened 2018-12-05 11:52 UTC
* cattrs version: 0.9.0
* Python version: 3.6
* Operating System: Ubuntu 18.04

### Description

structure is converting None to 'None' when it is set to a str field.

### What I Did

```
dataclass = partial(attrs, auto_attribs=True, frozen=True)

@dataclass
class BaseData:
    def to_dict(self):
        return asdict(self)

@dataclass
class A(BaseData):
    a: str
    b: str

print(structure({'a': 'asd', 'b': None}, A))
>>> A(a='asd', b='None')
```

**Comment by madsmtm** [comment] 2019-01-24 20:47
I can reproduce in `0.9.1.dev0`, the latest `master`, using a simpler example:
```py
>>> import attr, cattr
>>> @attr.s
>>> class Model:
...     a: str = attr.ib()
...
>>> cattr.structure({"a": None}, Model)
Model(a='None')
```
The issue is related to #26, and arise due to the type coercion of `str`

**Comment by Tinche** [comment] 2024-11-23 21:22
Going to close this as wontfix.

The solution here is to define your own structure hook for `str` that does an isinstance check instead of calling `str` on the value.

See https://catt.rs/en/stable/defaulthooks.html#primitive-values for more details.

**Closed** 2024-11-23 21:22 UTC
